server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bid-system
    username: hongti
    password: bid@123456

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: hongti
    password: bid@123456
    baseline-description: "init"
    baseline-version: 0

jwt:
  private-key: classpath:certs/privateKey.pem
  public-key: classpath:certs/publicKey.pem
